# Generated by Django 4.2 on 2024-04-12 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'permissions': [('can_edit_calendar', 'Can Edit Calendar')]},
        ),
    ]
